In [1]:
import nltk

In [2]:
import pandas as pd
import numpy as np

In [69]:
data_frame=pd.read_csv("Dataset/AllProductReviews-change.csv")

In [70]:
data_frame

,ID,ReviewTitle,ReviewBody,ReviewStar,Product
0,1,Honest review of an edm music lover\n,No doubt it has a great bass and to a great ex...,3,boAt Rockerz 255
1,2,Unreliable earphones with high cost\n,"This earphones are unreliable, i bought it be...",1,boAt Rockerz 255
2,3,Really good and durable.\n,"i bought itfor 999,I purchased it second time,...",4,boAt Rockerz 255
3,4,stopped working in just 14 days\n,Its sound quality is adorable. overall it was ...,1,boAt Rockerz 255
4,5,Just Awesome Wireless Headphone under 1000...ðŸ˜‰\n,Its Awesome... Good sound quality & 8-9 hrs ba...,5,boAt Rockerz 255
...,...,...,...,...,...
14332,14333,Good\n,Good\n,4,JBL T110BT
14333,14334,Amazing Product\n,An amazing product but a bit costly.\n,5,JBL T110BT
14334,14335,Not bad\n,Sound\n,1,JBL T110BT
14335,14336,a good product\n,the sound is good battery life is good but the...,5,JBL T110BT
14336,14337,"Average headphones , n overrated name\n",M writing this review after using for almost 7...,1,JBL T110BT

In [71]:
data_frame['review'] = data_frame['ReviewTitle']+data_frame["ReviewBody"]

In [72]:
data_frame

,ID,ReviewTitle,ReviewBody,ReviewStar,Product,review
0,1,Honest review of an edm music lover\n,No doubt it has a great bass and to a great ex...,3,boAt Rockerz 255,Honest review of an edm music lover\nNo doubt ...
1,2,Unreliable earphones with high cost\n,"This earphones are unreliable, i bought it be...",1,boAt Rockerz 255,Unreliable earphones with high cost\nThis ear...
2,3,Really good and durable.\n,"i bought itfor 999,I purchased it second time,...",4,boAt Rockerz 255,"Really good and durable.\ni bought itfor 999,I..."
3,4,stopped working in just 14 days\n,Its sound quality is adorable. overall it was ...,1,boAt Rockerz 255,stopped working in just 14 days\nIts sound qua...
4,5,Just Awesome Wireless Headphone under 1000...ðŸ˜‰\n,Its Awesome... Good sound quality & 8-9 hrs ba...,5,boAt Rockerz 255,Just Awesome Wireless Headphone under 1000...ðŸ˜‰...
...,...,...,...,...,...,...
14332,14333,Good\n,Good\n,4,JBL T110BT,Good\nGood\n
14333,14334,Amazing Product\n,An amazing product but a bit costly.\n,5,JBL T110BT,Amazing Product\nAn amazing product but a bit ...
14334,14335,Not bad\n,Sound\n,1,JBL T110BT,Not bad\nSound\n
14335,14336,a good product\n,the sound is good battery life is good but the...,5,JBL T110BT,a good product\nthe sound is good battery life...
14336,14337,"Average headphones , n overrated name\n",M writing this review after using for almost 7...,1,JBL T110BT,"Average headphones , n overrated name\nM writi..."

In [73]:
data_frame=data_frame.drop(["ReviewTitle","ReviewBody"],axis=1)

In [74]:
#Remove the review that contains no text
data_frame = data_frame[data_frame['review'] != '']
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14337 entries, 0 to 14336
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          14337 non-null  int64
 1   ReviewStar  14337 non-null  int64
 2   Product     14337 non-null  object
 3   review      14337 non-null  object
dtypes: int64(2), object(2)
memory usage: 560.0+ KB

In [75]:
#Making all review to lowercase
data_frame['review'] = data_frame['review'].str.lower()

In [76]:
data_frame

,ID,ReviewStar,Product,review
0,1,3,boAt Rockerz 255,honest review of an edm music lover\nno doubt ...
1,2,1,boAt Rockerz 255,unreliable earphones with high cost\nthis ear...
2,3,4,boAt Rockerz 255,"really good and durable.\ni bought itfor 999,i..."
3,4,1,boAt Rockerz 255,stopped working in just 14 days\nits sound qua...
4,5,5,boAt Rockerz 255,just awesome wireless headphone under 1000...ðŸ˜‰...
...,...,...,...,...
14332,14333,4,JBL T110BT,good\ngood\n
14333,14334,5,JBL T110BT,amazing product\nan amazing product but a bit ...
14334,14335,1,JBL T110BT,not bad\nsound\n
14335,14336,5,JBL T110BT,a good product\nthe sound is good battery life...
14336,14337,1,JBL T110BT,"average headphones , n overrated name\nm writi..."

In [77]:
data_frame['rating'] = [1 if rating > 3 else 0 for rating in data_frame['ReviewStar']]

In [78]:
data_frame=data_frame.drop(["ReviewStar"],axis=1)

In [79]:
data_frame

,ID,Product,review,rating
0,1,boAt Rockerz 255,honest review of an edm music lover\nno doubt ...,0
1,2,boAt Rockerz 255,unreliable earphones with high cost\nthis ear...,0
2,3,boAt Rockerz 255,"really good and durable.\ni bought itfor 999,i...",1
3,4,boAt Rockerz 255,stopped working in just 14 days\nits sound qua...,0
4,5,boAt Rockerz 255,just awesome wireless headphone under 1000...ðŸ˜‰...,1
...,...,...,...,...
14332,14333,JBL T110BT,good\ngood\n,1
14333,14334,JBL T110BT,amazing product\nan amazing product but a bit ...,1
14334,14335,JBL T110BT,not bad\nsound\n,0
14335,14336,JBL T110BT,a good product\nthe sound is good battery life...,1
14336,14337,JBL T110BT,"average headphones , n overrated name\nm writi...",0

In [80]:
data_frame['rating'].value_counts()

1    9402
0    4935
Name: rating, dtype: int64

In [81]:
#Checking if the dataset contains null values
data_frame.isnull().sum()

ID         0
Product    0
review     0
rating     0
dtype: int64

In [82]:
#Function to split string to tokens and removing punctuation
def identify_tokens(row):
    tokens = nltk.word_tokenize(row)
    token_words = [w for w in tokens if w.isalpha()]
    return token_words

In [83]:
#Tokenization of DataFrame
data_frame['review'] = data_frame["review"].apply(identify_tokens)

In [84]:
data_frame

,ID,Product,review,rating
0,1,boAt Rockerz 255,"[honest, review, of, an, edm, music, lover, no...",0
1,2,boAt Rockerz 255,"[unreliable, earphones, with, high, cost, this...",0
2,3,boAt Rockerz 255,"[really, good, and, durable, i, bought, itfor,...",1
3,4,boAt Rockerz 255,"[stopped, working, in, just, days, its, sound,...",0
4,5,boAt Rockerz 255,"[just, awesome, wireless, headphone, under, it...",1
...,...,...,...,...
14332,14333,JBL T110BT,"[good, good]",1
14333,14334,JBL T110BT,"[amazing, product, an, amazing, product, but, ...",1
14334,14335,JBL T110BT,"[not, bad, sound]",0
14335,14336,JBL T110BT,"[a, good, product, the, sound, is, good, batte...",1
14336,14337,JBL T110BT,"[average, headphones, n, overrated, name, m, w...",0

In [85]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [86]:
#Funtion for lemmatizing the list of words
def stem_list(row):
    lem_list = [lemmatizer.lemmatize(word) for word in row]
    return (lem_list)

In [87]:
#Stemming of the dataframe
data_frame['review'] = data_frame["review"].apply(stem_list)

In [88]:
data_frame

,ID,Product,review,rating
0,1,boAt Rockerz 255,"[honest, review, of, an, edm, music, lover, no...",0
1,2,boAt Rockerz 255,"[unreliable, earphone, with, high, cost, this,...",0
2,3,boAt Rockerz 255,"[really, good, and, durable, i, bought, itfor,...",1
3,4,boAt Rockerz 255,"[stopped, working, in, just, day, it, sound, q...",0
4,5,boAt Rockerz 255,"[just, awesome, wireless, headphone, under, it...",1
...,...,...,...,...
14332,14333,JBL T110BT,"[good, good]",1
14333,14334,JBL T110BT,"[amazing, product, an, amazing, product, but, ...",1
14334,14335,JBL T110BT,"[not, bad, sound]",0
14335,14336,JBL T110BT,"[a, good, product, the, sound, is, good, batte...",1
14336,14337,JBL T110BT,"[average, headphone, n, overrated, name, m, wr...",0

In [89]:
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))
stops.remove("not")
stops.remove("but")
stops.remove("no")

In [90]:
#Function to remove stop words from the list of words
def remove_stops(row):
    meaningful_words = [w for w in row if not w in stops]
    return (meaningful_words)

In [91]:
#Removing stopwords from the Dataframe
data_frame['review'] = data_frame["review"].apply(remove_stops)

In [92]:
data_frame

,ID,Product,review,rating
0,1,boAt Rockerz 255,"[honest, review, edm, music, lover, no, doubt,...",0
1,2,boAt Rockerz 255,"[unreliable, earphone, high, cost, earphone, u...",0
2,3,boAt Rockerz 255,"[really, good, durable, bought, itfor, purchas...",1
3,4,boAt Rockerz 255,"[stopped, working, day, sound, quality, adorab...",0
4,5,boAt Rockerz 255,"[awesome, wireless, headphone, awesome, good, ...",1
...,...,...,...,...
14332,14333,JBL T110BT,"[good, good]",1
14333,14334,JBL T110BT,"[amazing, product, amazing, product, but, bit,...",1
14334,14335,JBL T110BT,"[not, bad, sound]",0
14335,14336,JBL T110BT,"[good, product, sound, good, battery, life, go...",1
14336,14337,JBL T110BT,"[average, headphone, n, overrated, name, writi...",0

In [93]:
#Function to join the processed words
def rejoin_words(row):
    joined_words = ( " ".join(row))
    return joined_words

In [94]:
#Joining the processed words in the data_frame
data_frame['review'] = data_frame["review"].apply(rejoin_words)

In [95]:
data_frame

,ID,Product,review,rating
0,1,boAt Rockerz 255,honest review edm music lover no doubt ha grea...,0
1,2,boAt Rockerz 255,unreliable earphone high cost earphone unrelia...,0
2,3,boAt Rockerz 255,really good durable bought itfor purchased sec...,1
3,4,boAt Rockerz 255,stopped working day sound quality adorable ove...,0
4,5,boAt Rockerz 255,awesome wireless headphone awesome good sound ...,1
...,...,...,...,...
14332,14333,JBL T110BT,good good,1
14333,14334,JBL T110BT,amazing product amazing product but bit costly,1
14334,14335,JBL T110BT,not bad sound,0
14335,14336,JBL T110BT,good product sound good battery life good but ...,1
14336,14337,JBL T110BT,average headphone n overrated name writing rev...,0

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
#X contains review, y contains the ratings
X_train, X_test, y_train, y_test = train_test_split(data_frame[['review']], data_frame['rating'])

In [98]:
X_train.shape, X_test.shape

((10752, 1), (3585, 1))

In [99]:
from collections import Counter
Counter(y_train), Counter(y_test)

(Counter({0: 3688, 1: 7064}), Counter({1: 2338, 0: 1247}))

In [100]:
#Step 1: Using POS Tags

In [101]:
import textblob
pos_family = {
    'noun' : ['NN','NNS','NNP','NNPS'],
    'pron' : ['PRP','PRP$','WP','WP$'],
    'verb' : ['VB','VBD','VBG','VBN','VBP','VBZ'],
    'adj' :  ['JJ','JJR','JJS'],
    'adv' :  ['RB','RBR','RBS','WRB']
}

# function to check and get the part of speech tag count of a words in a given sentence
def check_pos_tag(x, flag):
    count = 0
    sentence = textblob.TextBlob(x)
    for tup in sentence.tags:
        ppo = list(tup)[1]
        if ppo in pos_family[flag]:
            count += 1
    return count

X_train['noun_count'] = X_train['review'].apply(lambda x: check_pos_tag(x, 'noun'))
X_train['verb_count'] = X_train['review'].apply(lambda x: check_pos_tag(x, 'verb'))
X_train['adj_count'] = X_train['review'].apply(lambda x: check_pos_tag(x, 'adj'))
X_train['adv_count'] = X_train['review'].apply(lambda x: check_pos_tag(x, 'adv'))
X_train['pron_count'] = X_train['review'].apply(lambda x: check_pos_tag(x, 'pron'))

X_test['noun_count'] = X_test['review'].apply(lambda x: check_pos_tag(x, 'noun'))
X_test['verb_count'] = X_test['review'].apply(lambda x: check_pos_tag(x, 'verb'))
X_test['adj_count'] = X_test['review'].apply(lambda x: check_pos_tag(x, 'adj'))
X_test['adv_count'] = X_test['review'].apply(lambda x: check_pos_tag(x, 'adv'))
X_test['pron_count'] = X_test['review'].apply(lambda x: check_pos_tag(x, 'pron'))

In [102]:
X_train

,review,noun_count,verb_count,adj_count,adv_count,pron_count
13716,defective bad defective peace,1,0,3,0,0
4216,ok but dint go rather buy wired earphone boat ...,12,3,3,2,0
10090,awesome bass cristal clean sound build quality...,3,1,4,0,0
1582,good mobile packed earphone bass powerful but ...,6,3,6,3,0
8972,loving purchased house marley earin loving pur...,7,6,1,1,0
...,...,...,...,...,...,...
9559,best earphone mic affordable price best earpho...,11,3,7,4,0
599,not satisfied sound quality heavy bass not bal...,11,6,5,5,0
13229,bass letdown good but bass big downer hardly b...,4,1,4,2,0
8306,amazed sound quality sound delivers par earpho...,12,5,4,1,0
10464,goof material delicate handle quality good,3,0,3,0,0

In [103]:
#Step 2: Using Lexical Methods

In [104]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyser = SentimentIntensityAnalyzer()

In [105]:
X_train['negative'] = X_train['review'].apply(lambda x: analyser.polarity_scores(x)["neg"])
X_test['negative'] = X_test['review'].apply(lambda x: analyser.polarity_scores(x)["neg"])
X_train['positive'] = X_train['review'].apply(lambda x: analyser.polarity_scores(x)["pos"])
X_test['positive'] = X_test['review'].apply(lambda x: analyser.polarity_scores(x)["pos"])
X_train['neutral'] = X_train['review'].apply(lambda x: analyser.polarity_scores(x)["neu"])
X_test['neutral'] = X_test['review'].apply(lambda x: analyser.polarity_scores(x)["neu"])
X_train['compound'] = X_train['review'].apply(lambda x: analyser.polarity_scores(x)["compound"])
X_test['compound'] = X_test['review'].apply(lambda x: analyser.polarity_scores(x)["compound"])

In [106]:
from textblob import TextBlob
X_train['subjectivity'] = X_train['review'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
X_test['subjectivity'] = X_test['review'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

In [107]:
X_train

,review,noun_count,verb_count,adj_count,adv_count,pron_count,negative,positive,neutral,compound,subjectivity
13716,defective bad defective peace,1,0,3,0,0,0.727,0.273,0.000,-0.7003,0.666667
4216,ok but dint go rather buy wired earphone boat ...,12,3,3,2,0,0.270,0.060,0.670,-0.7684,0.500000
10090,awesome bass cristal clean sound build quality...,3,1,4,0,0,0.208,0.456,0.336,0.5719,0.640000
1582,good mobile packed earphone bass powerful but ...,6,3,6,3,0,0.350,0.206,0.443,-0.7362,0.535417
8972,loving purchased house marley earin loving pur...,7,6,1,1,0,0.054,0.357,0.588,0.7716,0.950000
...,...,...,...,...,...,...,...,...,...,...,...
9559,best earphone mic affordable price best earpho...,11,3,7,4,0,0.000,0.391,0.609,0.9468,0.487500
599,not satisfied sound quality heavy bass not bal...,11,6,5,5,0,0.170,0.000,0.830,-0.6259,0.662500
13229,bass letdown good but bass big downer hardly b...,4,1,4,2,0,0.000,0.351,0.649,0.6602,0.466667
8306,amazed sound quality sound delivers par earpho...,12,5,4,1,0,0.000,0.408,0.592,0.8860,0.366667
10464,goof material delicate handle quality good,3,0,3,0,0,0.000,0.506,0.494,0.4767,0.750000

In [108]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [109]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [110]:
lr.fit(X_train.drop(['review'], axis=1), y_train)
predictions = lr.predict(X_test.drop(['review'], axis=1))
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78      1247
           1       0.88      0.89      0.89      2338

    accuracy                           0.85      3585
   macro avg       0.84      0.83      0.83      3585
weighted avg       0.85      0.85      0.85      3585

In [238]:
print(accuracy_score(y_test, predictions))

0.8507670850767085

In [239]:
print(confusion_matrix(y_test, predictions))

[[ 967  280]
 [ 255 2083]]